import type { Metadata } from "next";
import {Manrope, Inter} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/ui/custom/header";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const interfont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen w-full bg-background font-manrope antialiased",manrope.variable)}
      >
        <Header/>
        <h1></h1>
        <main>{children}</main>
      </body>
    </html>
  );
}
