import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/ui/custom/header";
import type { ReactNode } from "react";
// Simple server-side CartProvider fallback to avoid missing module during development
function CartProvider({ children }: { children: ReactNode }) {
  return <>{children}</>;
}

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const interfont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-background font-manrope antialiased",
          manrope.variable
        )}
      >
        <CartProvider>   {/* 👈 WRAP EVERYTHING HERE */}
          <Header />
          <main>{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}

